### ISSUE TITLE
No test.launch in the packages

### ISSUE THREAD

**Issue by 7675t** [at-wat/mcl_3dl#163]
We cannot launch the demo because the released packages don't contain test.launch. Please add setting to  CMakeLists.txt . Thanks.

**Comment by 7675t** [comment]
And config directory is missing.

**Comment by at-wat** [comment]
Thank you for your report!
Since a release needs roughly half-month in average due to the ROS-distro sync timing, please try the demo by cloning source package at this moment.

**Comment by 7675t** [comment]
Yes, I did, and can see your demo. Thanks!

**Comment by at-wat** [comment]
The released package in shadow-fixed now has launch and config.
This will be released to main repo by next distro-sync.
