### ISSUE TITLE
without IMU

### ISSUE THREAD

**Issue by weisongwen** [at-wat/mcl_3dl#223]

**Comment by at-wat** [comment]
I added `~fake_imu` parameter which disable subscribing `/imu/data` and use odometry pose as a pose measurement source.
Please try a new demo: https://github.com/at-wat/mcl_3dl/blob/master/doc/ExperimentalDemos.md#demo-without-imu-very-experimental

**Comment by at-wat** [comment]
Fake IMU mode, that uses odometry poses as IMU data, is added by #234.
Set `fake_imu` true to enable this.
