### ISSUE TITLE
How to use Landmark with mcl_3dl???

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/mcl_3dl#255]
Hi

I read and find that there's a cbLandmark loop inside the mcl_3dl.cpp. Please share with us on how to use it, and how to make the landmark.

Best,
Samuel

**Comment by at-wat** [comment]
mcl_3dl receives `geometry_msgs/PoseWithCovarianceStamped` messages from `/mcl_measurement` topic.
By using this topic, you can directly provide likelihood distribution of the robot pose to the particle filter.

**Comment by at-wat** [comment]
Closing as the question looks resolved. Feel free to reopen, or open a new issue, if you have any another question on this topic.
