### ISSUE TITLE
Robot movement needs to follow ROS frame convention?

### ISSUE THREAD

**Issue by tuandle** [at-wat/mcl_3dl#286]
Hi @at-wat ,
In my case, the odometry estimation comes from my VIO, hence, in the local odom frame, the forward movement happens along the y-axis as in this picture:
![ask_mcl](https://user-images.githubusercontent.com/18464308/74949007-67b57d00-53fd-11ea-81b0-5c733b5f23ef.png)
Do we need to transform the local odom frame to match the global map frame followed ROS convention? 
When I directly use the VIO as odometry sources, the result looks like this:
![ask_mcl2](https://user-images.githubusercontent.com/18464308/74949702-65075780-53fe-11ea-92a1-f76dd43199cf.png)
The pointcloud comes from a TOF camera and it can not align with the map. 
I would like to ask if there are some frames alignments (between map, odometry, base_link, pointcloud, IMU) that need to be done before starting the filter?
Thanks for your help!

**Comment by at-wat** [comment]
Sorry for delayed reply.
Current implementation uses IMU acceleration vector to obtain the ground direction.
So, I guess you need to adjust IMU frame relative to base_link in your case.
