### ISSUE TITLE
Curious - with the tf transform for map->floor

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/mcl_3dl#336]
Hi @at-wat 

Why is there a need for publishing the map->floor transform? What's the concept of needing this transform?

Best,
Samuel

**Comment by at-wat** [comment]
I used `floor` frame for visualization. When robot climbs to the second or higher floor, global origin on the ground is too far from the robot position.

**Comment by HappySamuel** [comment]
Hi @at-wat 

That's a nice design. I never thought that the visualization of robot on a multi-floor map can be handled like this.

Best,
Samuel
