### ISSUE TITLE
Timestamp of published TF is too old.

### ISSUE THREAD

**Issue by at-wat** [at-wat/mcl_3dl#44]
The time-stamp must be future dated according to the localization frequency.
Current implementation is time::now() + duration(0.2).

**Comment by HappySamuel** [comment]
Hi @at-wat 

Why do we need a future date tf timestamps?

Best,
Samuel

**Comment by at-wat** [comment]
see http://wiki.ros.org/tf/FAQ#Why_do_I_see_negative_average_delay_in_tf_monitor.3F

**Comment by HappySamuel** [comment]
Hi @at-wat 

Thank you very much.

Best,
Samuel
